[versions]
guava = "33.4.6-jre"
junit = "4.13.2"
junit-v4-v13 = "3.2.19.0"
scala-library = "3.7.3"
scala-xml = "2.3.0"
scalatest = "3.2.19"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-v4-v13 = { module = "org.scalatestplus:junit-5-10_3", version.ref = "junit-v4-v13" }
scala-library = { module = "org.scala-lang:scala3-library_3", version.ref = "scala-library" }
scala-xml = { module = "org.scala-lang.modules:scala-xml_3", version.ref = "scala-xml" }
scalatest = { module = "org.scalatest:scalatest_3", version.ref = "scalatest" }
